apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata: 
  name: web-color-dev
  namespace: argocd
spec: 
  destination:
    namespace: web-color-dev
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: dev
    repoURL: https://github.com/Carloshenripvh/k8s-web-color-page.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

--- 

apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata: 
  name: web-color-prod
  namespace: argocd
spec: 
  destination:
    namespace: web-color-prod
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: prod
    repoURL: https://github.com/Carloshenripvh/k8s-web-color-page.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true